version: '3'

services:
  selenium:
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
    restart: always

  app:
    build:
      context: .
    ports:
      - 5005:5000
    volumes:
      - ./app:/app
    command: sh -c "python3 -m flask run --host=0.0.0.0"
    depends_on:
      - selenium